### PR TITLE
Feature: Safe services/pipelines

### PR DESCRIPTION
**Pull request by serradura**
Context: 
--------
I've been working the codebase to receive this new feature. The main idea will be to expose a new kind of pipelines and services which will generate a failure when happening an exception during their executions.

This idea/need has been discussed in this issue: #2 

### To-dos:
- [x] Implement safe services
  * `Micro::Service::Safe`
  * `Micro::Service::Strict::Safe`

- [x] Implement safe pipelines
  * `Micro::Service::Pipeline::Safe`
  * `include Micro::Service::Pipeline::Safe`
  * `&` (composition operator)

- [x] Raise exceptions from the wrong usage of Micro::Service

- [x] Ensure the behavior of different types of safe services (`Micro::Service::{Safe,Strict::Safe}`) within validation mode

- [x] Failure(exception) will return a result with the ”:exception” type for any kind of Service (Base, Strict or Safe)

- [x] When the Failure method receives only a Symbol as its argument the result type and value will be the same. That is, the default type ”:error” will be replaced by it. e.g: `result = Failure(:not_an_integer); result.type == :not_an_integer && result.value == :not_an_integer`. Why? Because, failure results expose its service, so, in the case of a failure the user could use the type to control the flow and the service data within it.

- [x] Add to_proc method into services and pipelines
  * `Micro::Service::Base.to_proc`
  * `Micro::Service::Strict.to_proc`
  * `Micro::Service::Safe.to_proc`
  * `Micro::Service::Strict::Safe.to_proc`
  * `Micro::Service::Pipeline::Reducer#to_proc`
  * `Micro::Service::Pipeline::SafeReducer#to_proc`

- [x] Update README/Docs

- [x] Bump version to 1.0.0

### CODE REVIEW

**Comment by serradura** [comment]
@ekampp I began to work in an idea to address this issue with exceptions.

**The basic idea:**
Add new kind of services and pipelines to generate a failure if an exception happening during their executions.

**Question:**
What do you think about the usage of `&` to be the operator to compound safe pipelines?

```ruby
module Users
  Create = ProcessParams & ValidateParams & Persist & SendToCRM
end
```

**Comment by ekampp** [comment]
As I read this (and I'm not fluent in the mini-test framework, so bear with me here): This will propagate the internal error outside of the pipeline, but be a kind of Micro::Service::Result, right?

But will that solve the problem that a successful result triggers actually raises an exception?

**Comment by serradura** [comment]
> As I read this (and I'm not fluent in the mini-test framework, so bear with me here): This will propagate the internal error outside of the pipeline, but be a kind of Micro::Service::Result, right?

Yes, you got right.

> But will that solve the problem that a successful result triggers actually raises an exception?

Yes, because any exception will be wrapped in a result.

Example:
```ruby
require 'logger'

AppLogger = Logger.new(STDOUT)

class Divide < Micro::Service::Safe
  attributes :a, :b

  def call!
    Success(a / b) if a.is_a?(Integer) && b.is_a?(Integer)
    Failure(:not_an_integer)
  end
end

result = Divide.call(a: 2, b: 0)
result.type == :exception             # true
result.value.is_a?(ZeroDivisionError) # true

result.on_failure(:exception) do |exception|
  AppLogger.error(exception.message) # E, [2019-08-21T00:05:44.195506 #9532] ERROR -- : divided by 0
end

#===============================================#
# If you need a specific error handling,        #
# I suggest the usage of a case statement. e.g: #
#===============================================#

result.on_failure(:exception) do |exception, service|
  case exception
  when ZeroDivisionError then AppLogger.error(exception.message)
  else AppLogger.debug("#{service.class.name} was the service responsible for the exception")
  end
end
```

**Comment by ekampp** [comment]
What . happens if I want to do exception handling inside the `call!` method? E.g. from your example, how would I handle internal exceptions like this?

```ruby
class Divide < Micro::Service::Safe
  attributes :a, :b

  def call!
    return Success(a / b) if a.is_a?(Integer) && b.is_a?(Integer)
    Failure(:not_an_integer)
  rescue => error
    p error # => This will still be hit on a Success result
  end
end
```

**Comment by serradura** [comment]
> What . happens if I want to do exception handling inside the `call!` method? E.g. from your example, how would I handle internal exceptions like this?
> 
> ```ruby
> class Divide < Micro::Service::Safe
>   attributes :a, :b
> 
>   def call!
>     return Success(a / b) if a.is_a?(Integer) && b.is_a?(Integer)
>     Failure(:not_an_integer)
>   rescue => error
>     p error # => This will still be hit on a Success result
>   end
> end
> ```
@ekampp In this case, you will need to define failure. I just made a new commit [testing this behavior and improving the result type definition for failures with exceptions (for safe services only)](https://github.com/serradura/u-service/pull/4/commits/a6d0a8aa5d28d1f062484eaa0d5a17c4fb08b6fb#diff-0aa5c21a30b9413efbcde748a87930c8). 

So, if you rescue something will be your responsibility to define the service result. The safe services are an alternative to create flows without exceptions, that is, you can define a result hook (.eg:  `result.on_failure(:exception) { #... }`) [to define how your application will respond at the end of some safe Service/Pipeline execution](https://github.com/serradura/u-service/pull/4/files#diff-3512f2645036038c058e08c6bafe7f80R85-R104).

**Comment by ekampp** [comment]
I like how [this looks](https://github.com/serradura/u-service/pull/4/commits/a6d0a8aa5d28d1f062484eaa0d5a17c4fb08b6fb#diff-0aa5c21a30b9413efbcde748a87930c8R105-R113). Do I interpret this correctly, so that it enables me to do this: 

```
  def call!
    Success(a / b) if a.is_a?(Integer) && b.is_a?(Integer)
  rescue => error
    # report error
    # then bubble up error
    Failure(:not_an_integer)
  end
```

And this will not fall into the rescue block when it's actually a success?

**Comment by serradura** [comment]
> I like how [this looks](https://github.com/serradura/u-service/pull/4/commits/a6d0a8aa5d28d1f062484eaa0d5a17c4fb08b6fb#diff-0aa5c21a30b9413efbcde748a87930c8R105-R113). Do I interpret this correctly, so that it enables me to do this:
> 
> ```
>   def call!
>     Success(a / b) if a.is_a?(Integer) && b.is_a?(Integer)
>   rescue => error
>     # report error
>     # then bubble up error
>     Failure(:not_an_integer)
>   end
> ```
> 
> And this will not fall into the rescue block when it's actually a success?

That's right 👍

**Pull request merged**
